baseUrl = "http://0.0.0.0/"
languageCode = "en-US"
title = "Hugo Frais theme"
theme = "hugo-frais"


[Params]
    author = "Olivier Fredon"
    pseudo = "the2ne"
    twitter = "the2ne"
    github = "the2ne"
    linkedin = "the2ne"
    headline = "Hugo Frais"
    description = "This is the sites description, which will be found in the meta tags."

[taxonomies]
    category = "categories"
    tag = "tags"

[[menu.main]]
    name = "Posts"
    pre = ""
    url = "/post/"
    identifier = "post"
    weight = 1
[[menu.main]]
    name = "About"
    pre = ""
    url = "/about/"
    identifier = "about"
    weight = 2
